'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import {
  FileText,
  Download,
  Calendar,
  Filter,
  Search,
  BarChart3,
  TrendingUp,
  TrendingDown,
  DollarSign,
  Eye,
  Trash2,
  Plus,
  ChevronDown,
  Activity
} from 'lucide-react';
import { useUserStore } from '@/store/userStore';
import { formatCurrency, formatDate } from '@/lib/utils';
import { cn } from '@/lib/utils';
import jsPDF from 'jspdf';
import * as XLSX from 'xlsx';

interface Report {
  id: string;
  name: string;
  type: 'financial' | 'expense' | 'revenue' | 'custom';
  dateRange: string;
  generatedAt: string;
  generatedBy: string;
  status: 'completed' | 'generating' | 'failed';
  fileUrl?: string;
}

interface ReportFilters {
  dateRange: string;
  department: string;
  category: string;
  reportType: string;
}

export default function ReportsPage() {
  const router = useRouter();
  const { user, isAuthenticated, isLoading } = useUserStore();
  const [reports, setReports] = useState<Report[]>([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [showGenerateModal, setShowGenerateModal] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [filters, setFilters] = useState<ReportFilters>({
    dateRange: 'last30days',
    department: 'all',
    category: 'all',
    reportType: 'financial'
  });

  useEffect(() => {
    if (!isLoading && !isAuthenticated) {
      router.push('/auth/login');
    }
  }, [isAuthenticated, isLoading, router]);

  useEffect(() => {
    if (isAuthenticated) {
      fetchReports();
    }
  }, [isAuthenticated]);

  const fetchReports = async () => {
    try {
      // Mock data for demonstration
      const mockReports: Report[] = [
        {
          id: '1',
          name: 'Monthly Financial Summary',
          type: 'financial',
          dateRange: 'Oct 2024',
          generatedAt: new Date().toISOString(),
          generatedBy: user?.name || 'Current User',
          status: 'completed',
          fileUrl: '/reports/monthly-summary-oct-2024.pdf'
        },
        {
          id: '2',
          name: 'Q3 Expense Report',
          type: 'expense',
          dateRange: 'Jul-Sep 2024',
          generatedAt: new Date(Date.now() - 86400000).toISOString(),
          generatedBy: 'Finance Manager',
          status: 'completed',
          fileUrl: '/reports/q3-expense-2024.xlsx'
        },
        {
          id: '3',
          name: 'Revenue Analysis',
          type: 'revenue',
          dateRange: 'Last 90 days',
          generatedAt: new Date(Date.now() - 172800000).toISOString(),
          generatedBy: user?.name || 'Current User',
          status: 'completed',
          fileUrl: '/reports/revenue-analysis-90days.csv'
        },
      ];
      setReports(mockReports);
    } catch (error) {
      console.error('Failed to fetch reports:', error);
    }
  };

  const generateReport = async (format: 'pdf' | 'excel' | 'csv') => {
    setIsGenerating(true);
    try {
      // Mock report generation
      const reportData = [
        { Date: '2024-10-01', Type: 'Revenue', Amount: 5000, Description: 'Client Payment' },
        { Date: '2024-10-02', Type: 'Expense', Amount: 1200, Description: 'Office Supplies' },
        { Date: '2024-10-03', Type: 'Revenue', Amount: 3500, Description: 'Consulting Services' },
        { Date: '2024-10-04', Type: 'Expense', Amount: 800, Description: 'Software License' },
        { Date: '2024-10-05', Type: 'Revenue', Amount: 7200, Description: 'Product Sales' },
      ];

      const reportName = `${filters.reportType}-report-${formatDate(new Date())}`;

      if (format === 'pdf') {
        const doc = new jsPDF();
        doc.setFontSize(16);
        doc.text('Financial Report', 20, 20);
        doc.setFontSize(12);
        doc.text(`Generated: ${formatDate(new Date())}`, 20, 35);
        doc.text(`Generated by: ${user?.name}`, 20, 45);
        
        let yPosition = 65;
        doc.setFontSize(10);
        doc.text('Date | Type | Amount | Description', 20, yPosition);
        yPosition += 10;
        
        reportData.forEach(row => {
          doc.text(`${row.Date} | ${row.Type} | ${formatCurrency(row.Amount)} | ${row.Description}`, 20, yPosition);
          yPosition += 8;
        });
        
        doc.save(`${reportName}.pdf`);
      } else if (format === 'excel') {
        const ws = XLSX.utils.json_to_sheet(reportData);
        const wb = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(wb, ws, 'Financial Report');
        XLSX.writeFile(wb, `${reportName}.xlsx`);
      } else if (format === 'csv') {
        const ws = XLSX.utils.json_to_sheet(reportData);
        const csv = XLSX.utils.sheet_to_csv(ws);
        const blob = new Blob([csv], { type: 'text/csv' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${reportName}.csv`;
        a.click();
        URL.revokeObjectURL(url);
      }

      // Add to reports list
      const newReport: Report = {
        id: Date.now().toString(),
        name: `${filters.reportType} Report`,
        type: filters.reportType as Report['type'],
        dateRange: filters.dateRange,
        generatedAt: new Date().toISOString(),
        generatedBy: user?.name || 'Current User',
        status: 'completed'
      };
      
      setReports(prev => [newReport, ...prev]);
      setShowGenerateModal(false);
    } catch (error) {
      console.error('Failed to generate report:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  const filteredReports = reports.filter(report => {
    const matchesSearch = report.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
                          report.type.toLowerCase().includes(searchTerm.toLowerCase());
    return matchesSearch;
  });

  if (isLoading || !isAuthenticated || !user) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
      </div>
    );
  }

  const getReportTypeColor = (type: string) => {
    switch (type) {
      case 'financial':
        return 'bg-blue-100 text-blue-800';
      case 'expense':
        return 'bg-red-100 text-red-800';
      case 'revenue':
        return 'bg-green-100 text-green-800';
      case 'custom':
        return 'bg-purple-100 text-purple-800';
      default:
        return 'bg-gray-100 text-gray-800';
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'completed':
        return 'bg-green-100 text-green-800';
      case 'generating':
        return 'bg-yellow-100 text-yellow-800';
      case 'failed':
        return 'bg-red-100 text-red-800';
      default:
        return 'bg-gray-100 text-gray-800';
    }
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <div className="bg-card border-b border-border">
        <div className="px-4 sm:px-6 lg:px-8 py-6">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-2xl font-bold text-foreground">Reports & Analytics</h1>
              <p className="text-muted-foreground">Generate and export financial reports</p>
            </div>
            <button
              onClick={() => setShowGenerateModal(true)}
              className="flex items-center gap-2 px-4 py-2 bg-primary text-primary-foreground rounded-md hover:bg-primary/90 transition-colors"
            >
              <Plus className="h-4 w-4" />
              Generate Report
            </button>
          </div>
        </div>
      </div>

      {/* Quick Stats */}
      <div className="px-4 sm:px-6 lg:px-8 py-6">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
          <div className="bg-card rounded-lg border border-border p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-muted-foreground">Total Reports</p>
                <p className="text-2xl font-bold text-foreground">{reports.length}</p>
              </div>
              <div className="h-8 w-8 rounded-full bg-blue-100 flex items-center justify-center">
                <FileText className="h-4 w-4 text-blue-600" />
              </div>
            </div>
          </div>

          <div className="bg-card rounded-lg border border-border p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-muted-foreground">This Month</p>
                <p className="text-2xl font-bold text-foreground">8</p>
              </div>
              <div className="h-8 w-8 rounded-full bg-green-100 flex items-center justify-center">
                <TrendingUp className="h-4 w-4 text-green-600" />
              </div>
            </div>
          </div>

          <div className="bg-card rounded-lg border border-border p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-muted-foreground">Last Export</p>
                <p className="text-sm font-bold text-foreground">2 hours ago</p>
              </div>
              <div className="h-8 w-8 rounded-full bg-purple-100 flex items-center justify-center">
                <Download className="h-4 w-4 text-purple-600" />
              </div>
            </div>
          </div>

          <div className="bg-card rounded-lg border border-border p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-muted-foreground">Storage Used</p>
                <p className="text-2xl font-bold text-foreground">124 MB</p>
              </div>
              <div className="h-8 w-8 rounded-full bg-orange-100 flex items-center justify-center">
                <Activity className="h-4 w-4 text-orange-600" />
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Search and Filters */}
      <div className="px-4 sm:px-6 lg:px-8 pb-6">
        <div className="flex flex-col sm:flex-row gap-4">
          <div className="flex-1 relative">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <input
              type="text"
              placeholder="Search reports..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full pl-10 pr-3 py-2 border rounded-md bg-background text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:border-transparent"
            />
          </div>
          <select className="px-3 py-2 border rounded-md bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:border-transparent">
            <option value="all">All Types</option>
            <option value="financial">Financial</option>
            <option value="expense">Expense</option>
            <option value="revenue">Revenue</option>
            <option value="custom">Custom</option>
          </select>
        </div>
      </div>

      {/* Reports List */}
      <div className="px-4 sm:px-6 lg:px-8">
        <div className="bg-card rounded-lg border border-border">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-muted">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-muted-foreground uppercase tracking-wider">
                    Report Name
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-muted-foreground uppercase tracking-wider">
                    Type
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-muted-foreground uppercase tracking-wider">
                    Date Range
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-muted-foreground uppercase tracking-wider">
                    Generated By
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-muted-foreground uppercase tracking-wider">
                    Generated At
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-muted-foreground uppercase tracking-wider">
                    Status
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-muted-foreground uppercase tracking-wider">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {filteredReports.map((report) => (
                  <tr key={report.id} className="hover:bg-muted/50">
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="flex items-center">
                        <FileText className="h-4 w-4 text-muted-foreground mr-2" />
                        <div className="text-sm font-medium text-foreground">
                          {report.name}
                        </div>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className={cn(
                        "inline-flex px-2 py-1 text-xs font-semibold rounded-full",
                        getReportTypeColor(report.type)
                      )}>
                        {report.type}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-muted-foreground">
                      {report.dateRange}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-muted-foreground">
                      {report.generatedBy}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-muted-foreground">
                      {formatDate(report.generatedAt)}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className={cn(
                        "inline-flex px-2 py-1 text-xs font-semibold rounded-full",
                        getStatusColor(report.status)
                      )}>
                        {report.status}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-muted-foreground">
                      <div className="flex items-center space-x-2">
                        <button className="text-primary hover:text-primary/80">
                          <Eye className="h-4 w-4" />
                        </button>
                        <button className="text-muted-foreground hover:text-foreground">
                          <Download className="h-4 w-4" />
                        </button>
                        <button className="text-destructive hover:text-destructive/80">
                          <Trash2 className="h-4 w-4" />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      {/* Generate Report Modal */}
      {showGenerateModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
          <div className="bg-card rounded-lg border border-border w-full max-w-md mx-4">
            <div className="p-6 border-b border-border">
              <h2 className="text-lg font-semibold text-foreground">Generate New Report</h2>
            </div>
            <div className="p-6 space-y-4">
              <div>
                <label className="block text-sm font-medium text-foreground mb-1">
                  Report Type
                </label>
                <select
                  value={filters.reportType}
                  onChange={(e) => setFilters(prev => ({ ...prev, reportType: e.target.value }))}
                  className="w-full px-3 py-2 border rounded-md bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:border-transparent"
                >
                  <option value="financial">Financial Summary</option>
                  <option value="expense">Expense Report</option>
                  <option value="revenue">Revenue Report</option>
                  <option value="custom">Custom Report</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-foreground mb-1">
                  Date Range
                </label>
                <select
                  value={filters.dateRange}
                  onChange={(e) => setFilters(prev => ({ ...prev, dateRange: e.target.value }))}
                  className="w-full px-3 py-2 border rounded-md bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:border-transparent"
                >
                  <option value="last7days">Last 7 days</option>
                  <option value="last30days">Last 30 days</option>
                  <option value="last90days">Last 90 days</option>
                  <option value="thismonth">This Month</option>
                  <option value="lastmonth">Last Month</option>
                  <option value="thisquarter">This Quarter</option>
                  <option value="thisyear">This Year</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-foreground mb-1">
                  Export Format
                </label>
                <div className="grid grid-cols-3 gap-2">
                  <button
                    onClick={() => generateReport('pdf')}
                    disabled={isGenerating}
                    className="flex items-center justify-center gap-2 px-3 py-2 border border-border rounded-md hover:bg-muted transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    <FileText className="h-4 w-4" />
                    PDF
                  </button>
                  <button
                    onClick={() => generateReport('excel')}
                    disabled={isGenerating}
                    className="flex items-center justify-center gap-2 px-3 py-2 border border-border rounded-md hover:bg-muted transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    <BarChart3 className="h-4 w-4" />
                    Excel
                  </button>
                  <button
                    onClick={() => generateReport('csv')}
                    disabled={isGenerating}
                    className="flex items-center justify-center gap-2 px-3 py-2 border border-border rounded-md hover:bg-muted transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    <Download className="h-4 w-4" />
                    CSV
                  </button>
                </div>
              </div>

              <div className="flex justify-end space-x-3 pt-4">
                <button
                  onClick={() => setShowGenerateModal(false)}
                  className="px-4 py-2 text-sm font-medium text-muted-foreground hover:text-foreground"
                >
                  Cancel
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}