"""Initial migration

Revision ID: 415311ec16dc
Revises: 
Create Date: 2025-12-20 18:55:28.309641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '415311ec16dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(length=17),
               type_=sa.Enum('APPROVAL_REQUEST', 'APPROVAL_DECISION', 'REPORT_READY', 'SYSTEM_ALERT', 'DEADLINE_REMINDER', 'BUDGET_EXCEEDED', 'EXPENSE_CREATED', 'EXPENSE_UPDATED', 'EXPENSE_APPROVED', 'REVENUE_CREATED', 'REVENUE_UPDATED', 'REVENUE_APPROVED', 'SALE_CREATED', 'SALE_POSTED', 'FORECAST_CREATED', 'ML_TRAINING_COMPLETE', 'INVENTORY_LOW', 'INVENTORY_UPDATED', name='notificationtype'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'type',
               existing_type=sa.Enum('APPROVAL_REQUEST', 'APPROVAL_DECISION', 'REPORT_READY', 'SYSTEM_ALERT', 'DEADLINE_REMINDER', 'BUDGET_EXCEEDED', 'EXPENSE_CREATED', 'EXPENSE_UPDATED', 'EXPENSE_APPROVED', 'REVENUE_CREATED', 'REVENUE_UPDATED', 'REVENUE_APPROVED', 'SALE_CREATED', 'SALE_POSTED', 'FORECAST_CREATED', 'ML_TRAINING_COMPLETE', 'INVENTORY_LOW', 'INVENTORY_UPDATED', name='notificationtype'),
               type_=sa.VARCHAR(length=17),
               existing_nullable=False)
    # ### end Alembic commands ###
